name: Build_App
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build APK
        run: bash ./gradlew assembleDebug
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: SecureGuard_APK
          path: app/build/outputs/apk/debug/app-debug.apk
